{{- if eq .Values.autoUpdate.enabled true }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jx-boot-upgrade
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: boot-upgrade
            release: jx
        spec:
          containers:
          - args:
            - boot 
            - upgrade       
            command:
            - jx            
            image: docker.io/macox/jx:1.0.23
            imagePullPolicy: Always
            name: boot-upgrade
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File            
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          serviceAccountName: tekton-bot
  successfulJobsHistoryLimit: 3
  schedule: {{ .Values.autoUpdate.schedule | default "0 12 */5 * *" | quote }}
  suspend: false
{{- end }}
